server:
  context-path: /
  port: 8080
  session:
    persistent: true

spring:
#  mail:
#    host: ${HOST_MAIL}
#    port: ${PORT_MAIL}
#    protocol: smtp
#    username: ${USERNAME_MAIL}
#    password: ${PASSWORD_MAIL}
#    encoding: UTF-8
#    from:
#      enabled: true
#      defaultsender: ${SENDER_MAIL}
#    smtps:
#      auth: true
#      starttls:
#        enable: true
#    properties:
#      mail:
#        debug: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BD_USER}
    password: ${BD_PASSWORD}
    url: ${BD_JDBC_URL}
#    hikari:
#      connection-init-sql: SELECT 1 FROM DUAL
#      connection-test-query: SELECT 1 FROM DUAL
#      connection-timeout: 600000
#      idle-timeout: 600000
#      leak-detection-threshold: 500000
#      max-lifetime: 1800000
#      maximum-pool-size: ${MAX_POOL_SIZE:2}
#      validation-timeout: 5000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update #validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

app:
  description: '@project.description@'
  encoding: '@project.build.sourceEncoding@'
  java-version: '@java.version@'
  msg: Project Spring boot
  name: '@project.name@'
  version: '@project.version@'
